add portscanner
LuD1161/CyberSecurity-IIITA pull request #8
Opened 2017-07-03 04:18 UTC by GYeyosi

2017-07-03 13:14 UTC, LuD1161 requested changes
Minor Changes

2017-07-03 13:14 UTC, LuD1161 commented on portscanner/blacklist.json
> +	"31":{
Why are you writing **'31'** instead it should be sequential , cause `port_number` key is being used for that.

2017-07-03 13:14 UTC, LuD1161 commented on portscanner/blacklist.json
> +	"service": "SubSeven server (default for V1.0-2.0"
Where is the closing bracket **)** ?

2017-07-03 13:14 UTC, LuD1161 commented on portscanner/scanner.py
> +        t.start()
is this working ?
cause the indentation doesn't seem right .

2017-07-03 13:33 UTC, GYeyosi commented on portscanner/blacklist.json
> +	"31":{
to access a particular port it would be easy if we have the same port number itself there instead some random sequential number.

2017-07-03 13:34 UTC, GYeyosi commented on portscanner/blacklist.json
> +	"service": "SubSeven server (default for V1.0-2.0"
This was mistake done while i was writing blacklist.json file. we will correct it and update it soon.

2017-07-03 13:37 UTC, LuD1161 commented on portscanner/blacklist.json
> +	"31":{
@GYeyosi 
sounds good but then we won't need the `port_number` key.
Or if any specific reason for the same , please let me know

2017-07-03 13:37 UTC, LuD1161 commented on portscanner/blacklist.json
> +	"service": "SubSeven server (default for V1.0-2.0"
>we will correct it
I suppose it's your PR ?

2017-07-03 13:38 UTC, GYeyosi commented on portscanner/scanner.py
> +        t.start()
I didn't get why it is showing wrong indentation here. It's working and please look at the code at this link .
https://github.com/GYeyosi/CyberSecurity-IIITA/blob/master/portscanner/scanner.py

2017-07-03 13:39 UTC, LuD1161 requested changes

2017-07-03 13:39 UTC, LuD1161 commented on portscanner/sample_output.json
> +    "1234": {
@GYeyosi 
Here change it to sequential , cause the front-end won't know the ports beforehand.

2017-07-03 13:53 UTC, LuD1161 commented on portscanner/scanner.py
> +        t.start()
:+1:

2017-07-04 19:20 UTC, Jayanth-N commented
Sir, we can add these ports too in blacklist.json......as if they are open then there would be some unintended service for sure
[blist.txt](https://github.com/LuD1161/CyberSecurity-IIITA/files/1122903/blist.txt)
https://en.wikipedia.org/wiki/List_of_TCP_and_UDP_port_numbers#cite_note-rfc4960-12

2017-07-05 07:02 UTC, LuD1161 approved these changes

2017-07-05 07:02 UTC, LuD1161 commented
@GYeyosi 
is it complete ?

2017-07-06 13:37 UTC, GYeyosi commented
@LuD1161 sir,I am almost done with the idea I was having. Acharya tried doing in a different way scrapping for blacklist.json from 
http://www.colasoft.com/resources/ports_list.php
we are trying to develop the code with his ideas like showing newly open ports.
It would be definitely be better.

2017-07-06 14:52 UTC, Jayanth-N commented
@LuD1161  Sir,Is it that we should only see the registered ports? As this website contains both registered and unregistered!!Do we have to search for other website?

2017-07-09 04:51 UTC, LuD1161 commented
@GYeyosi @Jayanth-N 
Sorry , for the late reply .
There would be a **confidence** parameter ( add it to the json ) , which will contain rating from 1-10.
Right now , just which all are registered , give them 10 and unregistered give them 5.

2017-07-09 08:13 UTC, Jayanth-N commented
Okay......

2017-08-09 15:26 UTC, merged